name: 'AstarBase CI'

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
  defaults:
    run:
      working-directory: ./contract/shibuya

  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
       with:
          node-version: 16.x
          cache: yarn
    - run: npm install
    - run: npx hardhat test
